apiVersion: v1
kind: Endpoints
metadata:
  name: mlflow-db-service
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "5"
subsets:
  - addresses:
      - ip: 172.31.2.221
    ports:
      - port: 5432