apiVersion: v1
kind: Service
metadata:
  name: mlflow-db-service
  namespace: mlflow
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mlflow-db-service
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "5"
subsets:
  - addresses:
      - ip: 172.31.2.221
    ports:
      - port: 5432