apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base            
  - db-endpoints.yaml       
  - middleware.yaml          

commonLabels:
  env: prod-ish 

patches:
  - target:
      kind: Deployment
      name: mlflow
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1