apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sw5005-sus/ceramicraft-argocd-deploy.git
    targetRevision: HEAD
    path: bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sw5005-sus/ceramicraft-argocd-deploy.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/sw5005-sus/ceramicraft-argocd-deploy.git
        revision: HEAD
        directories:
          - path: helm_backend/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/sw5005-sus/ceramicraft-argocd-deploy.git
        targetRevision: HEAD
        path: charts                 
        helm:
          valueFiles:
            - '../helm_backend/{{.path.basename}}/values.yaml'
          releaseName: '{{.path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sw5005-sus/ceramicraft-argocd-deploy.git
    targetRevision: HEAD
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0
    helm:
      values: |
        injector:
          enabled: false
        server:
          ha:
            enabled: false
          replicas: 1
          standalone:
            enabled: true
            config: |
              ui = true
              
              listener "tcp" {
                address = "[::]:8200"
                tls_disable = true
              }
              
              # local storage for demo purposes, not recommended for production
              storage "file" {
                path = "/vault/data"
              }
              
              # AWS KMS Auto-unseal
              seal "awskms" {
                region     = "ap-southeast-1"    
                kms_key_id = "alias/ceramicraft-k3s-vault"
              }
          dataStorage:
            enabled: true
            size: 1Gi # sufficient for demo purposes
            storageClass: local-path
            accessMode: ReadWriteOnce
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: vault.local
                paths: ["/"]
          # open ui for demo purposes, not recommended for production
          ui:
            enabled: true
            serviceType: ClusterIP
  destination:
    # deploy to K3s
    server: https://kubernetes.default.svc
    # deploy to vault namespace
    namespace: vault 

  syncPolicy:
    automated:
      prune: true      # automatically delete resources that are no longer defined in Git
      selfHeal: true   # automatically revert changes made to resources that differ from Git
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.11
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sw5005-sus/ceramicraft-argocd-deploy.git
    path: k8s-configs # path store secret-store.yaml and external-secret-store.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.16.1 
    helm:
      values: |
        identity:
          externalCA: true  # tell linkerd to read CA from secret
          issuer:
            scheme: kubernetes.io/tls
        identityTrustAnchorsPEM: |
        # INSERT_CA_MARKER
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
