apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-secure-agent-ms-config
data:
  config.yml: |
    http:
      host: "0.0.0.0"
      port: 8080

    mysql:
      host: "middleware-internal-svc.default.svc.cluster.local"
      port: "3306"
      username: "root"
      database: "admin_db"
      max_connect_size: 5
    
    kafka:
      bootstrap_servers: middleware-internal-svc.default.svc.cluster.local:29092
      group_id: ceramicraft_ai_secure_agent_group

    redis:
      host: middleware-internal-svc.default.svc.cluster.local
      port: 6379