replicaCount: 1

image:
  repository: lian1280/ceramicraft-review-agent
  tag: 2.8.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  grpcPort: 3000

livenessProbe:
  path: /review-agent/v1/ping
  port: 3000
  initialDelaySeconds: 15
  periodSeconds: 10
readinessProbe:
  path: /review-agent/v1/ping
  port: 3000
  initialDelaySeconds: 15
  periodSeconds: 10

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

volumes:
  configMapName: review-agent-config
  logPath: /tmp/logs/review-agent

externalSecret:
  targetName: review-agent-secrets

extraEnv:
  - name: BATCH_CRON_SCHEDULE
    value: "*/2 * * * *"
  - name: LLM_API_BASEURL
    value: https://api.moonshot.cn/v1
  - name: LLM_MODEL
    value: kimi-k2-0711-preview
  - name: LLM_VISION_MODEL
    value: moonshot-v1-8k-vision-preview
  - name: LLM_TEMPERATURE
    value: "0"
  - name: LLM_VISION_TEMPERATURE
    value: "1"
  - name: RUN_ENV
    value: production
  - name: MCP_SERVER_URL
    value: http://mcp-server-svc:8080/mcp
  - name: MLFLOW_TRACKING_URI
    value: https://mlflow.ntdoc.site
  - name: AWS_DEFAULT_REGION
    value: ap-southeast-1
  - name: EMAIL_RECEIVER
    value: 1228lyric+4@gmail.com
