apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: zitadel-auth
  namespace: default
spec:
  forwardAuth:
    address: http://user-ms-svc.default.svc.cluster.local/oauth/v1/verify
    trustForwardHeader: true
    authResponseHeaders:
      - "X-Original-User-ID"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-routes
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    # User Service
    - match: PathPrefix(`/api/user-ms`) || PathPrefix(`/user-ms`)
      kind: Rule
      services:
        - name: user-ms-svc
          port: http
      middlewares:
        - name: zitadel-auth

    # Payment Service
    - match: PathPrefix(`/api/payment-ms`) || PathPrefix(`/payment-ms`)
      kind: Rule
      services:
        - name: payment-ms-svc
          port: http
      middlewares:
        - name: zitadel-auth

    # Order Service
    - match: PathPrefix(`/api/order-ms`) || PathPrefix(`/order-ms`)
      kind: Rule
      services:
        - name: order-ms-svc
          port: http
      middlewares:
        - name: zitadel-auth

    # Product Service
    - match: PathPrefix(`/api/product-ms`) || PathPrefix(`/product-ms`)
      kind: Rule
      services:
        - name: product-ms-svc
          port: http
      middlewares:
        - name: zitadel-auth

    # Comment Service
    - match: PathPrefix(`/api/comment-ms`) || PathPrefix(`/comment-ms`)
      kind: Rule
      services:
        - name: comment-ms-svc
          port: http
      middlewares:
        - name: zitadel-auth

