replicaCount: 1

image:
  repository: lian1280/ceramicraft-log-mservice
  tag: dev-202604050439
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  grpcPort: 50051

livenessProbe:
  path: /log-ms/v1/ping
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  path: /log-ms/v1/ping
  initialDelaySeconds: 30
  periodSeconds: 10

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

volumes:
  configMapName: log-ms-config
  logPath: /tmp/logs/log-ms
