# manifests/mlflow/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.10.0
        command: ["/bin/bash", "-c"]
        args:
          - |
<<<<<<< HEAD
            pip install --no-cache-dir psycopg2-binary==2.9.9 boto3==1.34.69 && \
=======
            pip install --no-cache-dir psycopg2==2.9.9 boto3==1.34.69 && \
>>>>>>> e22abfa ((fix): fix mlflow img)
            exec mlflow server \
            --host 0.0.0.0 \
            --port 5000 \
            --backend-store-uri postgresql://mlflow_user@mlflow-db-service:5432/mlflow_db \
            --default-artifact-root s3://ceramicraft-mlflow/
        ports:
        - containerPort: 5000
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: MLFLOW_DB_PASSWORD
        - name: MLFLOW_HTTP_REQUEST_TIMEOUT
          value: "300"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5