image:
  repository: profgamer/ceramicraft-auth-shim
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false # This service is internal to the cluster, called by Traefik
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []
# affinity: {}

