apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
  namespace: default
spec:
  refreshInterval: "1m" # refresh every 1 minute, adjust as needed
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ms-secret-vault # k8s secret name to create/update
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/ceramicraft