apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-external-secret
  namespace: mlflow
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mlflow-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/mlflow