apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-secure-agent-external-secret
  namespace: default
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ai-secure-agent-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/ceramicraft/ai_secure_agent_config
    - extract:
        key: secret/ceramicraft