apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
  namespace: vault
spec:
  refreshInterval: "1m" # refresh every 1 minute, adjust as needed
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: k8s-app-secret # k8s secret name to create/update
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD # K8s Secret Key
      remoteRef:
        key: myapp/config    # Vault path
        property: password   # Vault 里的 Key