replicaCount: 1

image:
  repository: lian1280/ceramicraft-ai-secure-agent
  tag: debug-202604071410
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  grpcPort: 5001

livenessProbe:
  path: /ai-secure-agent-ms/v1/ping
  initialDelaySeconds: 10
  periodSeconds: 5
readinessProbe:
  path: /ai-secure-agent-ms/v1/ping
  initialDelaySeconds: 10
  periodSeconds: 5

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 345Mi

volumes:
  configMapName: ai-secure-agent-ms-config
  logPath: /tmp/logs/ai-secure-agent-ms
  mountPath: /app/resources/config.yml
  subPath: config.yml

podAnnotations:
  linkerd.io/inject: disabled

extraEnv:
  - name: ENABLE_MLFLOW_TRACING
    value: "true"
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow-tracking-svc.mlflow.svc.cluster.local:5000"
  - name: CONFIG_PATH
    value: "/app/resources/config.yml"
  - name: MALLOC_ARENA_MAX
    value: "2"