replicaCount: 1

image:
  repository: lian1280/ceramicraft-customer-support-agent-ui
  tag: dev-202604220822
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  grpcPort: 8081

livenessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
readinessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

volumes:
  configMapName: customer-support-agent-ui-config
  mountPath: /etc/nginx/extra
  logPath: /tmp/logs/customer-support-agent-ui

externalSecret:
  targetName: customer-support-agent-ui-secrets

extraEnv:
  - name: VITE_AGENT_BASE_URL
    value: "https://support.ntdoc.site"
  - name: VITE_ZITADEL_CLIENT_ID
    value: "369270211708226724"
  - name: VITE_ZITADEL_REDIRECT_URI
    value: "https://support.ntdoc.site/callback"
  - name: VITE_USER_MS_BASE_URL
    value: "https://support.ntdoc.site"
